#!/usr/bin/env sh
set -eu

usage() {
  echo "Usage: $0 --write|--check" >&2
}

if [ "$#" -ne 1 ]; then
  usage
  exit 2
fi

mode=$1
case "$mode" in
  --write|--check) ;;
  *)
    usage
    exit 2
    ;;
esac

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/ai-central-apm-generate.XXXXXX")
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

bundles=$(
  sed -n '/^[[:space:]]*"bundles": \[/,/^[[:space:]]*\]/p' \
    "$repo_root/templates/catalog.json" |
    sed -n 's/^[[:space:]]*"id": "\([^"]*\)",[[:space:]]*$/\1/p'
)

render_manifest() {
  bundle=$1
  install_dir=$tmp_dir/install-$bundle
  manifest=$tmp_dir/$bundle-apm.yml
  seen_paths=$tmp_dir/$bundle-seen-paths
  description=$(
    awk -v bundle_id="$bundle" '
      $0 ~ "\"id\": \"" bundle_id "\"," { found = 1 }
      found && /"description":/ {
        line = $0
        sub(/^[[:space:]]*"description": "/, "", line)
        sub(/",?[[:space:]]*$/, "", line)
        print line
        exit
      }
    ' "$repo_root/templates/catalog.json"
  )
  mkdir -p "$install_dir"
  : >"$seen_paths"

  if [ -z "$description" ]; then
    echo "Missing catalog description for bundle: $bundle" >&2
    exit 1
  fi

  "$repo_root/scripts/install-skill-bundle.sh" \
    "$install_dir" --bundle "$bundle" --mode link >/dev/null

  {
    echo "name: ai-central-$bundle"
    echo "version: 0.2.0"
    echo "description: $description"
    echo "repository: https://github.com/dills122/ai-central"
    echo "keywords:"
    echo "  - ai"
    echo "  - agent-skills"
    echo "  - codex"
    echo "  - $bundle"
    echo "type: skill"
    echo "includes: auto"
    echo
    echo "# Generated by scripts/generate-apm-bundles.sh from the shell bundle."
    echo "# templates/ remains the authoritative skill source."
    echo "dependencies:"
    echo "  apm:"

    find "$install_dir/.agents/skills" -mindepth 1 -maxdepth 1 -type l | sort |
      while IFS= read -r link; do
        installed_name=$(basename "$link")
        source_path=$(readlink "$link")
        relative_path=${source_path#"$repo_root/"}
        natural_name=$(basename "$source_path")

        if [ "$relative_path" = "$source_path" ]; then
          echo "Skill link points outside the repository: $link -> $source_path" >&2
          exit 1
        fi

        # APM identifies local dependencies by source path, so one source cannot
        # be deployed twice under two aliases. Keep the first sorted installed
        # name; this affects only the historical duplicate in the `all` bundle.
        if grep -Fqx "$relative_path" "$seen_paths"; then
          continue
        fi
        echo "$relative_path" >>"$seen_paths"

        echo "    - path: ../../../$relative_path"
        if [ "$installed_name" != "$natural_name" ]; then
          echo "      alias: $installed_name"
        fi
      done
  } >"$manifest"

  destination=$repo_root/packages/apm/$bundle/apm.yml
  if [ "$mode" = "--write" ]; then
    mkdir -p "$(dirname "$destination")"
    cp "$manifest" "$destination"
    echo "generated packages/apm/$bundle/apm.yml"
  elif [ ! -f "$destination" ]; then
    echo "Missing generated APM manifest: packages/apm/$bundle/apm.yml" >&2
    exit 1
  elif ! cmp -s "$manifest" "$destination"; then
    echo "Stale generated APM manifest: packages/apm/$bundle/apm.yml" >&2
    diff -u "$destination" "$manifest" >&2 || true
    exit 1
  fi
}

for bundle in $bundles; do
  render_manifest "$bundle"
done

if [ "$mode" = "--check" ]; then
  echo "APM manifests match all catalog bundles"
fi
